### ISSUE TITLE
Crash when switch gamemode with F3+F4

### ISSUE THREAD

**Issue by SettingDust** [CCr4ft3r/ImmediatelyFastReforged#2]
Dawncraft mod pack
```
java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.asFloatBuffer()" because "this.f_85648_" is null
	at com.mojang.blaze3d.vertex.BufferBuilder.m_166794_(BufferBuilder.java:152) ~[client-1.18.2-20220404.173914-srg.jar%23344!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium.mixins.json:core.pipeline.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:APP:mixins.oculus.vertexformat.json:MixinBufferBuilder,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder_SegmentRendering,pl:mixin:APP:epicfight.mixins.json:MixinBufferBuilder,pl:mixin:APP:flywheel.mixins.json:BufferBuilderMixin,pl:mixin:APP:immediatelyfast.mixins.json:core.MixinBufferBuilder,pl:mixin:APP:mixins.oculus.compat.sodium.json:vertex_format.entity.MixinBufferBuilder_ExtendedVertexFormatCompat,pl:mixin:APP:irisflw.mixins.iris.json:MixinBufferBuilder,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.vertex.BufferBuilder.m_166771_(BufferBuilder.java:87) ~[client-1.18.2-20220404.173914-srg.jar%23344!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:rubidium.mixins.json:core.pipeline.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:APP:mixins.oculus.vertexformat.json:MixinBufferBuilder,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder_SegmentRendering,pl:mixin:APP:epicfight.mixins.json:MixinBufferBuilder,pl:mixin:APP:flywheel.mixins.json:BufferBuilderMixin,pl:mixin:APP:immediatelyfast.mixins.json:core.MixinBufferBuilder,pl:mixin:APP:mixins.oculus.compat.sodium.json:vertex_format.entity.MixinBufferBuilder_ExtendedVertexFormatCompat,pl:mixin:APP:irisflw.mixins.iris.json:MixinBufferBuilder,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType.m_110412_(RenderType.java:363) ~[client-1.18.2-20220404.173914-srg.jar%23344!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:immediatelyfast.mixins.json:core.MixinRenderLayer,pl:mixin:APP:wildbackport-common.mixins.json:access.RenderTypeAccessor,pl:mixin:APP:mixins.oculus.json:rendertype.RenderTypeAccessor,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:RenderTypeAccessor,pl:mixin:APP:flywheel.mixins.json:RenderTypeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.raphimc.immediatelyfast.feature.core.BatchableImmediate._draw(BatchableImmediate.java:37) ~[ImmediatelyFastReforged-1.18.2-1.1.10.jar%23188!/:1.18.2-1.1.10] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.m_109912_(ImmediateAdapter.java:123) ~[ImmediatelyFastReforged-1.18.2-1.1.10.jar%23188!/:1.18.2-1.1.10] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?] {}
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601) ~[?:?] {}
	at net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.m_173043_(ImmediateAdapter.java:96) ~[ImmediatelyFastReforged-1.18.2-1.1.10.jar%23188!/:1.18.2-1.1.10] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.m_109911_(ImmediateAdapter.java:106) ~[ImmediatelyFastReforged-1.18.2-1.1.10.jar%23188!/:1.18.2-1.1.10] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115127_(ItemRenderer.java:259) ~[client-1.18.2-20220404.173914-srg.jar%23344!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174235_(ItemRenderer.java:299) ~[client-1.18.2-20220404.173914-srg.jar%23344!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174277_(ItemRenderer.java:290) ~[client-1.18.2-20220404.173914-srg.jar%23344!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115203_(ItemRenderer.java:270) ~[client-1.18.2-20220404.173914-srg.jar%23344!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.debug.GameModeSwitcherScreen$GameModeIcon.m_97607_(GameModeSwitcherScreen.java:51) ~[client-1.18.2-20220404.173914-srg.jar%23344!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.gui.screens.debug.GameModeSwitcherScreen$GameModeSlot.m_6303_(GameModeSwitcherScreen.java:241) ~[client-1.18.2-20220404.173914-srg.jar%23344!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	
```

**Comment by CCr4ft3r** [comment]
This issue seems not to be caused by using only mods of the official modpack plus ImmediatelyFast. I just tested switching gamemode and it works fine.
Do you use any other mods?

**Comment by SettingDust** [comment]
> This issue seems not to be caused by using only mods of the official modpack plus ImmediatelyFast. I just tested switching gamemode and it works fine. Do you use any other mods?

Dawncraft mod pack :D

**Comment by CCr4ft3r** [comment]
Since I cannot reproduce this error, I need further information. 
-Minimal setup (mods) to reproduce it
-Steps for reproducing it

This issue will be closed after one week if no further information will be provided
